<div class="team">
    <div class="teamWrap">
        <h1>About <font style="color:#0E76BC;">Data</font><font style="color:#ED1C24;">Plug</font></h1>
        <ul>
            <div class="teamMember">
                <li style="width: 100%;"> 
                    <p>
                        <font style="color:#0E76BC;font-size:15px;">Data</font><font style="color:#ED1C24;font-size:15px;">Plug</font> is plug-and-play platform for 'assembling' mobile applications for data gathering. With <font style="color:#0E76BC;font-size:13px;">Data</font><font style="color:#ED1C24;font-size:13px;">Plug</font>, there is no need to make bespoke application from scratch. Instead, you can assemble a mobile application in less than 5 minutes by simply dragging and dropping components.
                    </p>
                     <p>
                         Importantly, the application generated by <font style="color:#0E76BC;font-size:13px;">Data</font><font style="color:#ED1C24;font-size:13px;">Plug</font> is highly dynamic and can be remotely updated from a control panel (without needing a re-install on the phone or need to publish a new version to Google Play Store). This is particularly useful in scenarios where data gathering needs of a project evolve over time and it may be difficult to recall a large number of devices from the field for an application update.
                     </p>
                     <p>
                         The architecture of <font style="color:#0E76BC;font-size:13px;">Data</font><font style="color:#ED1C24;font-size:13px;">Plug</font> is motivated by a number of projects undertaken by the Government of Punjab, Pakistan to gather data from field workers using mobile applications (<a href="http://tribune.com.pk/story/631041/punjabs-model-of-m-governance" target="_new">Punjab’s model of m-governance</a>), e.g. <a href="https://play.google.com/store/apps/details?id=dengue.tracking.system" target="_new">Dengue Activity Tracking System</a>, <a href="https://play.google.com/store/apps/details?id=com.crimeinvestigationreporting.system" target="_new">Crime investigation Reporting System</a>, <a href="https://play.google.com/store/apps/details?id=com.spotpricing.pricecontrol" target="_new">Punjab Spot Pricing</a>, <a href="https://play.google.com/store/apps/details?id=com.agriculturalmonitoring.system" target="_new">Tracking of Agriculture Extension Workers</a>, <a href="https://play.google.com/store/apps/details?id=com.pmiuapplication" target="_new">Tracking of Education Monitoring officers</a> etc.
                    </p>
                    <p>
                        <font style="color:#0E76BC;font-size:13px;">Data</font><font style="color:#ED1C24;font-size:13px;">Plug</font> is inspired by UW’s Open Data Kit (ODK), aimed at making an open-source, standards-based mobile application authoring platform.<br />
                        The highly dynamic, scalable and intuitive design of <font style="color:#0E76BC;font-size:13px;">Data</font><font style="color:#ED1C24;font-size:13px;">Plug</font> makes it an ideal platform for government organizations, NGOs and other organizations interested in gathering data from field workers.
                    </p>
                    <p>
                        <font style="color:#0E76BC;font-size:13px;">Data</font><font style="color:#ED1C24;font-size:13px;">Plug</font> is an Open Source Platform developed by a team of researchers at <a href="http://itu.edu.pk" target="_new">Information Technology University</a>, with technical support from <a href="http://pitb.gov.pk" target="_new">Punjab Information Technology Board</a>, and funding by The World Bank and UK Aid.
                    </p>
                </li>
                
            </div>
            
        </ul>
    </div>
</div>
<div class="affiliationFeatured">
    <div class="affiliationWrap">
        <ul class="affulLft">
            <li> <img src="<?= base_url() ?>assets/home/images/itu.png" alt="Information Technology" /> </li>

        </ul>  
        <ul class="affulRt">
            <h3>Sponsored by</h3>

            <li class="sponsered"> <img src="<?= base_url() ?>assets/home/images/worldjob.png" alt="The World Bank" /> </li>
            <li class="sponsered"> <img src="<?= base_url() ?>assets/home/images/ukaid.png" alt="UkAid" /> </li>

        </ul>
    </div>
</div>
